name: Backup latest Apps Script Code

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10 */2 * * *'
    # “At minute 10 past every 2 hours.”
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out this repo
        uses: actions/checkout@v2
        
      - name: Create gitignore & claspignore 
        run: |
          if [ ! -e ".gitignore" ] ; then
            echo "creating .gitignore"
            echo ".clasp.json" > .gitignore
            echo "secrets.js" >> .gitignore
            echo "Secrets.js" >> .gitignore
          fi

          if [ ! -e ".claspignore" ] ; then
            echo "creating .claspignore"
            echo ".git" > .claspignore
            echo "Readme.md" >> .claspignore
            echo ".gitignore" >> .claspignore
          fi
    
      - name: restore secrets
        run: |
          echo '${{ secrets.CLASPRC }}' > ~/.clasprc.json
          echo '${{ secrets.CLASP }}' | jq ". + {rootDir: \"$(pwd)\"}" > .clasp.json

        
      - run: npx @google/clasp pull

      - if: always()
        run: rm -rf ~/.clasprc.json clasp.json

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Latest code: $(date -u)" || exit 0
          git push
      
      
